# Generated by Django 5.2 on 2025-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('tags', models.CharField(choices=[('tech', 'Tech'), ('cs', 'Computer Science'), ('ai', 'AI'), ('bio', 'Biology'), ('music', 'Music'), ('movies', 'Movies'), ('psychology', 'Psychology'), ('history', 'History'), ('books', 'Books & Literature'), ('fiction', 'Fiction'), ('gaming', 'Gaming'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
